
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EvidenciaServiceService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8888/evidencia?wsdl")
public class EvidenciaServiceService
    extends Service
{

    private final static URL EVIDENCIASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EVIDENCIASERVICESERVICE_EXCEPTION;
    private final static QName EVIDENCIASERVICESERVICE_QNAME = new QName("http://server/", "EvidenciaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/evidencia?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVIDENCIASERVICESERVICE_WSDL_LOCATION = url;
        EVIDENCIASERVICESERVICE_EXCEPTION = e;
    }

    public EvidenciaServiceService() {
        super(__getWsdlLocation(), EVIDENCIASERVICESERVICE_QNAME);
    }

    public EvidenciaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVIDENCIASERVICESERVICE_QNAME, features);
    }

    public EvidenciaServiceService(URL wsdlLocation) {
        super(wsdlLocation, EVIDENCIASERVICESERVICE_QNAME);
    }

    public EvidenciaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVIDENCIASERVICESERVICE_QNAME, features);
    }

    public EvidenciaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EvidenciaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EvidenciaService
     */
    @WebEndpoint(name = "EvidenciaServicePort")
    public EvidenciaService getEvidenciaServicePort() {
        return super.getPort(new QName("http://server/", "EvidenciaServicePort"), EvidenciaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EvidenciaService
     */
    @WebEndpoint(name = "EvidenciaServicePort")
    public EvidenciaService getEvidenciaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "EvidenciaServicePort"), EvidenciaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVIDENCIASERVICESERVICE_EXCEPTION!= null) {
            throw EVIDENCIASERVICESERVICE_EXCEPTION;
        }
        return EVIDENCIASERVICESERVICE_WSDL_LOCATION;
    }

}
